stages:
  data_download:
    cmd: dvc pull
  convert_notebooks:
    cmd: jupyter nbconvert --to script src/*.ipynb --output-dir src/

  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - params.yaml
      - data/raw/bank-full.csv
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - params.yaml
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv
    params:
      - model
      - mlflow
