data:
  train: "data/processed/train.csv"
  val: "data/processed/val.csv"
  test: "data/processed/test.csv"

mlflow:
  uri: "http://100.26.108.135:8080"
  experiment: "bank_marketing_remote"

model:
  n_estimators_list: [50, 100, 200]
  max_depth_list: [5, 10, null]

